[dev]
framework = "#custom"
command = "npm run snowpack:dev"
targetPort = 8080
port = 8000
publish = "build"
autoLaunch = false

[build]
command = "npm run build:netlify"
functions = "netlify-functions"
publish = "build"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = "script-src 'self' https://cdnjs.cloudflare.com https://code.iconify.design; child-src 'self'; object-src 'none';"
