[dev]
framework = "#custom"
command = "npm run dev:snowpack"
targetPort = 8080
port = 8000
publish = "build"
autoLaunch = false

[build]
command = "npm run netlify-build"
functions = "netlify-functions"
publish = "build"
[build.environment]
NPM_FLAGS = "--no-optional"


[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = "script-src 'self' https://cdnjs.cloudflare.com https://code.iconify.design; child-src 'self'; object-src 'none';"
