// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  CommentRight = 1,
  CommentLeft = 2,
  Comment = 3,
  Document = 4,
  Raw = 5,
  RawBlock = 6,
  BlockRight = 7,
  BlockNode = 8,
  BlockLeft = 9
