// This file was generated by lezer-generator. You probably shouldn't edit it.
import { Parser } from 'lezer'
import { NodeProp } from 'lezer'
export const parser = Parser.deserialize({
  version: 13,
  states: "#YOVQPOOPeOPOOOjQPO'#CdOOQO'#Cl'#ClOOQO'#Cg'#CgQVQPOOPrQPO'#C_POOO)C>_)C>_OOQO'#Cf'#CfOzQPO,59OOOQO,59O,59OOOQO-E6e-E6eP!SQPO,58yPOOO,58y,58yOOQO-E6d-E6dOOQO1G.j1G.jPOOO1G.e1G.e",
  stateData: '![~OQPQ~OTROUROXQO_SO~OQUO~OVYO^WO~OP]O^WO~OV_O^WO~OP`O^WO~O',
  goto: '}aPPPbPPPPePisPPPPyRVPTROTQXQQ[UT^X[QTORZTTSOT',
  nodeNames: '⚠ CommentRight CommentLeft Comment Document Raw RawBlock BlockRight BlockNode BlockLeft',
  maxTerm: 16,
  nodeProps: [
    [NodeProp.openedBy, 1,'CommentLeft'],
    [NodeProp.closedBy, 2,'CommentRight']
  ],
  skippedNodes: [0,1,2,3],
  repeatNodeCount: 2,
  tokenData: '%q~RZOYtYZyZ}t}!O!Q!O!bt!b!c!e!c!}t!}#O$f#O#Pt#P#Q%d#Q~t~yO^~~!QO^~_~~!VP^~}!O!Y~!]P#P#Q!`~!eOP~~!jQ^~!^!_!p!b!c#n~!sRO!`!p!`!a!|!a~!p~#PTO!`!p!`!a!|!a!b!p!b!c#`!c~!p~#eRU~O!`!p!`!a!|!a~!p~#qRO!b#n!b!c#z!c~#n~#}RO!b#n!b!c$W!c~#n~$]RT~O!b#n!b!c$W!c~#n~$kQ^~qr$q!}#O%S~$tP}!O$w~$zP}!O$}~%SOQ~~%XQX~z{%_!P!Q%_~%dOX~~%iP^~#P#Q%l~%qOV~',
  tokenizers: [0],
  topRules: { Document: [0,4] },
  tokenPrec: 0
})
